# Generated by Django 5.2.8 on 2025-12-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Bienvenue chez Codeshestergn', max_length=200)),
                ('hero_subtitle', models.TextField(default='Votre partenaire stratégique pour la maintenance informatique...')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('students_count', models.CharField(default='500+', max_length=50)),
                ('satisfaction_rate', models.CharField(default='98%', max_length=50)),
                ('years_expertise', models.CharField(default='10+', max_length=50)),
                ('support_hours', models.CharField(default='24/7', max_length=50)),
            ],
            options={
                'verbose_name': "Paramètres de l'accueil",
                'verbose_name_plural': "Paramètres de l'accueil",
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='home/partners/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
