# Generated by Django 6.0.1 on 2026-01-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('icon', models.CharField(help_text='Classe FontAwesome (ex: fas fa-laptop)', max_length=50, verbose_name='Icône')),
                ('description', models.TextField(verbose_name='Description de la catégorie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='maintenance/categories/', verbose_name="Image d'illustration")),
            ],
            options={
                'verbose_name': 'Catégorie de maintenance',
                'verbose_name_plural': 'Catégories de maintenance',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du service')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('price_start', models.CharField(max_length=50, verbose_name='Prix à partir de')),
                ('image', models.ImageField(blank=True, null=True, upload_to='maintenance/services/', verbose_name='Image du service')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='maintenance.maintenancecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Service de maintenance',
                'verbose_name_plural': 'Services de maintenance',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone/WhatsApp')),
                ('equipment_model', models.CharField(help_text='Ex: Epson L3110, Dell XPS 15', max_length=200, verbose_name="Modèle de l'équipement")),
                ('problem_description', models.TextField(verbose_name='Description du problème')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenanceservice', verbose_name='Service demandé')),
            ],
            options={
                'verbose_name': 'Demande de maintenance',
                'verbose_name_plural': 'Demandes de maintenance',
            },
        ),
    ]
